name: Build

on: 
  push: 
    tags:
      - '*'
defaults:
  run:
    working-directory: ./MailDispatcherAdmin
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install -g typescript
      - run: npm install -D @web-atoms/pack
      - run: npm install
      - run: tsc
      - run: node ./node_modules/@web-atoms/pack/index.js .
      - run: npm run test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
